- LICENSE
> Feature(Licence): Modified Proprietary licence to Commons Clause on top of MIT Licence.

- src/krisi/evaluate/__init__.py
- src/krisi/evaluate/evaluate.py
- src/krisi/evaluate/metric.py
- src/krisi/evaluate/scorecard.py
- src/krisi/evaluate/type.py
- src/krisi/examples/basic_report.py
- src/krisi/examples/basic_report_rolling.py
- src/krisi/utils/printing.py
- tests/test_evaluate.py
> chore(Refractor): Interface improvements

- .vscode/launch.json
- src/krisi/evaluate/assertions.py
- src/krisi/evaluate/metric.py
> feature(Assertions): Added checks for ``y`` and ``predictions``

- src/krisi/evaluate/assertions.py
- src/krisi/evaluate/evaluate.py
- src/krisi/evaluate/scorecard.py
> feature(Scorecard): Scorecard evaluates metrics

- src/krisi/evaluate/scorecard.py
- src/krisi/examples/basic_scorecard.py
> feature(Printing): Short summary of core statistics.

- src/krisi/evaluate/library/default_metrics.py
> feature(Metrics): Added more default metrics and info for previous ones.

- .vscode/launch.json
- README.md
- src/krisi/evaluate/scorecard.py
- src/krisi/examples/basic_report.py
- src/krisi/examples/basic_scorecard.py
- src/krisi/examples/extended_scorecard.py
- src/krisi/utils/printing.py
> feature(Examples): Updated examples and fixed rolling based printing.

- pyproject.toml
- src/krisi/evaluate/scorecard.py
- src/krisi/evaluate/type.py
- src/krisi/examples/saving.py
- src/krisi/utils/iterable_helpers.py
- src/krisi/utils/printing.py
> Feature(Saving): ``ScoreCard`` object and console summary can be saved now.

- .vscode/launch.json
- src/krisi/evaluate/compare.py
- src/krisi/evaluate/evaluate.py
- src/krisi/evaluate/scorecard.py
- src/krisi/evaluate/type.py
- src/krisi/examples/basic_loading.py
> Feature(Loading): Retrieval of all scorecards based on project name

- pyproject.toml
- tests/test_examples.py
> feature(Tests): Example integration tests added.

- docs/conf.py
- docs/index.rst
- src/krisi/evaluate/scorecard.py
- src/krisi/examples/basic_loading.py
> Docs(Docstrings): Added sklearn formatted docstrings to ``ScoreCard`` 

- .vscode/launch.json
- src/krisi/evaluate/assertions.py
- src/krisi/evaluate/eval.py
- src/krisi/evaluate/scorecard.py
- src/krisi/evaluate/utils.py
- src/krisi/examples/basic_scorecard.py
- src/krisi/examples/extended_scorecard.py
- tests/test_examples.py
> Feature(ScoreCard): Targets and Predictions are now directly supplied to ``ScoreCard``

- README.md
- src/krisi/__init__.py
- src/krisi/evaluate/__init__.py
- src/krisi/evaluate/score.py
- src/krisi/examples/basic_loading.py
- src/krisi/examples/basic_saving.py
- src/krisi/examples/compare_classification.py
- src/krisi/examples/compare_regression.py
- src/krisi/examples/minimal_classification.py
- src/krisi/examples/minimal_regression.py
> chore(Renaming): Renamed ``eval`` to ``score``

- README.md
> docs(Readme): Fixed errors.

- .github/workflows/black.yml
- src/krisi/evaluate/library/default_metrics_classification.py
- src/krisi/evaluate/library/default_metrics_regression.py
> feature(Metrics): added SMAPE and Matthew's correlation coefficient

- pyproject.toml
> feature(Packaging): Updated ``pyproject``

- .github/workflows/ci-cd.yml
- .github/workflows/publish.yml
> feature(CI): added publish workflow

- README.md
> docs(Readme): Updated image imports to be absolute for pypi.

- pyproject.toml
> chore(Bump): Bump commit message.

- .github/workflows/tests.yaml
- README.md
- pyproject.toml
- src/krisi/evaluate/library/diagrams.py
- src/krisi/report/interactive.py
- src/krisi/report/pdf.py
- src/krisi/report/type.py
> feature(Packaging): Conditional importing of libraries

- examples/basic_df.py
- src/krisi/evaluate/scorecard.py
> feature(Scorecard): Scorecard has a utility function to get it's metrics as a ``pd.dataseries``

- docs/images/logo.svg
> docs(Logo): Added new logo without white background.

- pyproject.toml
> fix: Dependency should be lower for python.

- pyproject.toml
> fix(Package): Python package version.

- src/krisi/report/__init__.py
- src/krisi/report/vizualise.py
- tests/test_report.py
> feature(Report): Vizualise util function for `predictions` and `targets`

- src/krisi/report/vizualise.py
- tests/test_report.py
> feature(Report): Added clearer vizualisation of prediction results.

- README.md
> feature(Docs): Badges as styled for external use on our website.

- src/krisi/report/vizualise.py
- tests/test_report.py
> feature(Vizualisation): Seperate y plot, fixed index issue.

- src/krisi/report/vizualise.py
- tests/test_report.py
> feature(Report): You can now pass in a `pd.Series` to `plot_y_predicions`.

- .flake8
- src/krisi/evaluate/dataset.py
> feature(Dataset): Added utils to check consistency of a dataset.

- README.md
- examples/a_full_rundown_notebook.ipynb
- examples/basic_report_rolling.py
- examples/basic_scorecard.py
- examples/default_metric_selection.py
- examples/extended_scorecard.py
- examples/minimal_classification.py
- examples/minimal_regression.py
- examples/training_arima_report.py
- src/krisi/evaluate/metric.py
- src/krisi/evaluate/scorecard.py
- src/krisi/report/console.py
- src/krisi/utils/printing.py
- tests/test_scorecard.py
> feature(Scorecard): Slicing Scorecard and printing multiple versions of the scorecard

- examples/a_full_rundown_notebook.ipynb
- examples/basic_scorecard.py
- examples/extended_scorecard.py
- examples/training_arima_report.py
- src/krisi/evaluate/metric.py
- src/krisi/evaluate/scorecard.py
- src/krisi/evaluate/type.py
> feature(Docs): Added explanation of the print function and fixed minor remaining error with the previous commit.

- .vscode/settings.json
- src/krisi/evaluate/compare.py
- src/krisi/evaluate/scorecard.py
- src/krisi/report/console.py
- src/krisi/utils/io.py
> feature(Report): Compare function now receives dataframe boolean to print a df rather than a formatted string.

- src/krisi/evaluate/compare.py
> fix(Report): Compare printing bold didn't work in jupyter notebook.

- README.md
- examples/printing_methods.py
- src/krisi/evaluate/scorecard.py
- src/krisi/report/console.py
- src/krisi/utils/io.py
> chore(Docs): Updated readme with Dream Faster suite.

- README.md
> chore(Docs): Renamed reference to fold-wrappers

- README.md
> fix(Docs): updated tests badge in README

- README.md
> fix(Docs): Updated readme with the correct example link.

- .github/workflows/bump-version.yaml
> feature(CI): added `bump-version` workflow

- docs/walkthroughs/a_full_rundown_notebook.ipynb
- pyproject.toml
- src/krisi/evaluate/group.py
- src/krisi/evaluate/library/default_metrics_regression.py
- src/krisi/evaluate/metric.py
- src/krisi/evaluate/scorecard.py
- src/krisi/utils/iterable_helpers.py
> feature(Metric): `Metric`s can be grouped now to make precalculating possible.

- docs/examples/basic_rolling.py
- src/krisi/evaluate/group.py
- src/krisi/evaluate/library/default_metrics_regression.py
- src/krisi/evaluate/metric.py
- src/krisi/evaluate/score.py
- src/krisi/evaluate/scorecard.py
- src/krisi/evaluate/type.py
- src/krisi/utils/devutils/timing.py
> feature(Rolling): Upgraded the rolling function and unified functions. We are using `pd.rolling` now.

- docs/examples/analyse_rolling_corr.py
- docs/examples/evaluate_rolling.py
- src/krisi/analyse/__init__.py
- src/krisi/analyse/correlations.py
- src/krisi/evaluate/library/default_metrics_regression.py
- src/krisi/evaluate/metric.py
- src/krisi/evaluate/scorecard.py
- src/krisi/evaluate/type.py
- src/krisi/report/graph.py
- src/krisi/report/interactive.py
> feature(Analyse): Exposed correlation over time metrics in `analyze` module.

- src/krisi/evaluate/scorecard.py
- src/krisi/evaluate/type.py
- src/krisi/evaluate/utils.py
- src/krisi/utils/io.py
- src/krisi/utils/iterable_helpers.py
- tests/unit/test_saving.py
> feature(ScoreCard): Saving now handles overwriting based on model_name

- src/krisi/evaluate/scorecard.py
- tests/unit/test_saving.py
> fix(ScoreCard): We should clean the directory first in tests and misspelling.

- src/krisi/evaluate/scorecard.py
> fix(ScoreCard): `ipython` should only be imported if notebook is available.

- src/krisi/evaluate/assertions.py
- src/krisi/utils/iterable_helpers.py
- tests/unit/test_infer.py
> fix(Utils): correctly recognize dataset types

- src/krisi/evaluate/scorecard.py
> fix(Printing): Scorecard get's printed multiple times to console.

- src/krisi/evaluate/library/default_metrics_classification.py
> feature(Metrics): added ncdg, changed default metrics slightly

- src/krisi/evaluate/metric.py
- src/krisi/evaluate/type.py
- tests/unit/test_evaluate.py
> fix(Evaluation): Sample weight rolling window fix.

- src/krisi/evaluate/metric.py
- src/krisi/utils/iterable_helpers.py
- tests/unit/test_evaluate.py
> fix(Evaluation): Rolling evaluation shouldn't assume the name of the arguments.

- src/krisi/evaluate/library/default_metrics_classification.py
- src/krisi/evaluate/library/default_metrics_regression.py
- src/krisi/evaluate/library/metric_wrappers.py
- src/krisi/evaluate/type.py
> feature(Library): Added Bennet's et. al `S-Score` classification metric.

- docs/examples/evaluate_compare_regression.py
- src/krisi/evaluate/library/default_metrics_classification.py
- src/krisi/evaluate/library/default_metrics_regression.py
- src/krisi/evaluate/library/diagrams.py
- src/krisi/evaluate/library/metric_wrappers.py
- src/krisi/report/library/console/diagrams.py
- src/krisi/utils/printing.py
- tests/test_scorecard.py
> feature(Report): Calibration plot in console & took out `rmse` from default metrics. 

- src/krisi/evaluate/library/default_metrics_classification.py
> feature(Library): added weighted metrics to binary presets

- src/krisi/utils/__init__.py
- src/krisi/utils/devutils/environment_checks.py
> fix(Tests): don't use matplotlib if not installed

- src/krisi/analyse/correlations.py
- src/krisi/report/graph.py
- src/krisi/report/report.py
- src/krisi/report/vizualise.py
- src/krisi/utils/__init__.py
- src/krisi/utils/devutils/environment_checks.py
> feature(Test): Don't show plots when we are testing.

- src/krisi/utils/data.py
> fix(Data): Syntethetic data generation.

- src/krisi/evaluate/library/default_metrics_regression.py
> fix(Library): put back rmse to default metrics

- docs/examples/evaluate_classification.py
- docs/examples/evaluate_classification_with_probabilities.py
- src/krisi/analyse/correlations.py
- src/krisi/evaluate/group.py
- src/krisi/evaluate/library/benchmarking.py
- src/krisi/evaluate/library/default_metrics_classification.py
- src/krisi/evaluate/metric.py
- src/krisi/evaluate/score.py
- src/krisi/evaluate/scorecard.py
- src/krisi/report/graph.py
> fix(Group): Group is now handled separately

- docs/examples/evaluate_classification.py
- docs/examples/evaluate_classification_with_probabilities.py
- src/krisi/evaluate/assertions.py
- src/krisi/evaluate/library/__init__.py
- src/krisi/evaluate/library/default_metrics_classification.py
- src/krisi/evaluate/scorecard.py
- src/krisi/evaluate/type.py
- src/krisi/report/report.py
- src/krisi/report/type.py
- src/krisi/report/vizualise.py
- src/krisi/utils/iterable_helpers.py
- tests/test_benchmarking.py
- tests/unit/test_infer.py
> feature(Library): added distinction between balanced vs imbalanced metrics

- src/krisi/evaluate/library/diagrams.py
- src/krisi/report/library/console/diagrams.py
> fix(Calibration): propagate pos_label throughout

- src/krisi/__init__.py
- src/krisi/utils/devutils/timing.py
> feature(Utils): Export `ParsableEnum`.

- src/krisi/evaluate/library/default_metrics_classification.py
- src/krisi/evaluate/library/metric_wrappers.py
- tests/test_imbalanced.py
> feature(Library): Added imbalance metrics.

- src/krisi/evaluate/library/benchmarking.py
- src/krisi/evaluate/metric.py
- src/krisi/utils/data.py
> feature(Analysis): Random model updated to have a smoothing factor.

- src/krisi/evaluate/scorecard.py
> fix(ScoreCard): ScoreCard indexing should return a copy not the actual object.

- src/krisi/evaluate/library/benchmarking.py
- src/krisi/utils/data.py
> feature(Evaluate): Random model has a shuffled chunk version.

- src/krisi/utils/data.py
> fix(Evaluate): Random chunking now supports length that are not wholly divisible by chunk_size.

- src/krisi/evaluate/library/default_metrics_classification.py
- src/krisi/evaluate/library/metric_wrappers.py
> feature(Metrics): added avg_precision metric

- src/krisi/evaluate/library/benchmarking.py
- tests/test_benchmarking.py
> fix(Evaluation): Benchmark metrics were switched around.

- .github/workflows/tests.yaml
- pyproject.toml
- src/krisi/analyse/correlations.py
- src/krisi/evaluate/library/default_metrics_regression.py
- src/krisi/evaluate/library/diagrams.py
- src/krisi/evaluate/library/metric_wrappers.py
- src/krisi/report/graph.py
- src/krisi/utils/data.py
> chore(Analysis): Matplotlib and Statsmodel dependency optional now.

- .flake8
- src/krisi/evaluate/library/__init__.py
> chore(Exporting): Export all metrics to be accessed from `krisi.library`.

- src/krisi/utils/data.py
> feature(Data): Shuffling in chunks updated to work with `copy_on_write = True`.

- src/krisi/evaluate/library/benchmarking.py
- src/krisi/utils/data.py
> feature(Modeling): Random model shuffling now accpets float as chunk_size.

- src/krisi/utils/data.py
- tests/unit/test_utils.py
> fix(Utils): shuffle_df_in_chunks should only shuffle indices, not the whole dataframe

- src/krisi/evaluate/type.py
> feature(Evaluation): New SampleTypes - Validation Sample.

- src/krisi/evaluate/library/benchmarking.py
- src/krisi/utils/data.py
> feature(Util): Handle datetime index in shuffling in chunks.

- src/krisi/utils/data.py
- tests/unit/test_utils.py
> feature(Utils): Combinatorial shuffling.

- src/krisi/evaluate/library/benchmarking.py
- src/krisi/utils/data.py
> chore(Utils): Smaller synthetic dataset to speed up testing.

- src/krisi/evaluate/type.py
> feature(Types): Updated types to be ParsableEnums.

- src/krisi/evaluate/scorecard.py
> feature(ScoreCard): ScoreCard `pd.Series` function should return metric keys as indexes.

- src/krisi/evaluate/scorecard.py
> fix(Printing): Took out annoying printing in debug mode.

- src/krisi/evaluate/group.py
- src/krisi/evaluate/metric.py
- src/krisi/evaluate/scorecard.py
- src/krisi/report/console.py
> fix(Printing): Handling debug and repr printing properly.

- src/krisi/evaluate/score.py
- src/krisi/evaluate/scorecard.py
> feature(Reporting & Types): ScoreCard arithmetic and `sample_type` can be also a string.

- src/krisi/evaluate/library/default_metrics_classification.py
> fix(Presets): adjusted balanced metric presets

- src/krisi/evaluate/scorecard.py
> fix(Union): Only apply function if the result is an int or a float.

- src/krisi/evaluate/scorecard.py
> fix(ScoreCard): `get_ds()` should not return `Group` type.

- src/krisi/evaluate/metric.py
- src/krisi/evaluate/scorecard.py
- tests/unit/test_scorecard_getters.py
> feature(Scorecard): Scorecard now has the option to get comparison results.

- src/krisi/evaluate/scorecard.py
- tests/unit/test_scorecard_getters.py
> feature(ScoreCard): Index by comparison result

- docs/examples/evaluate_compare_classification.py
- src/krisi/evaluate/scorecard.py
> fix(ScoreCard): Fail no unknown key.

- src/krisi/evaluate/metric.py
- src/krisi/evaluate/scorecard.py
- tests/unit/test_scorecard_union.py
> feature(ScoreCard): Union logic on comparison scores.

- src/krisi/evaluate/library/benchmarking.py
- tests/test_benchmarking.py
> fix(Benchmarking): Random model now receives `X` and random chunking fixed.

- src/krisi/evaluate/library/default_metrics_classification.py
- src/krisi/evaluate/library/metric_wrappers.py
- src/krisi/evaluate/metric.py
- tests/unit/test_metric.py
- tests/unit/test_scorecard_getters.py
> fix(Metric): Passing in sample_weights.

- .github/workflows/tests.yaml
- src/krisi/evaluate/group.py
- src/krisi/evaluate/library/benchmarking.py
- src/krisi/evaluate/metric.py
- src/krisi/evaluate/scorecard.py
- tests/unit/test_scorecard_getters.py
> feature(Metric): Metric is returned after evaluating.

- docs/examples/evaluate_classification.py
- docs/examples/evaluate_classification_with_probabilities.py
- docs/examples/evaluate_probabilities.py
- docs/examples/evaluate_probabilities_binary.py
- docs/examples/evaluate_rolling.py
- docs/walkthroughs/a_full_rundown_notebook.ipynb
- docs/walkthroughs/a_full_rundown_notebook.md
- src/krisi/evaluate/group.py
- src/krisi/evaluate/library/benchmarking.py
- src/krisi/evaluate/library/default_metrics_classification.py
- src/krisi/evaluate/library/default_metrics_regression.py
- src/krisi/evaluate/metric.py
- src/krisi/evaluate/score.py
- src/krisi/evaluate/scorecard.py
- src/krisi/evaluate/type.py
- tests/test_benchmarking.py
> feature(Benchmarking): Benchmarking is not a Group anymore.

- src/krisi/evaluate/benchmark.py
- tests/test_benchmarking.py
> fix(Reporting): Benchmarking didn't call model predict.

- src/krisi/evaluate/metric.py
- tests/test_benchmarking.py
> feature(Benchmarking): Optional property to disable benchmarking on a metric.
